"use client";

import { useState } from "react";
import type { AnalysisCenter as AnalysisCenterData } from "@/lib/api";

type Section = "performance" | "watchlist" | "national" | "channels" | "evidence" | "methodology";
const sections: { id: Section; label: string }[] = [
  { id: "performance", label: "Observed performance" }, { id: "watchlist", label: "Core six" },
  { id: "national", label: "National radar" }, { id: "channels", label: "Channels" },
  { id: "evidence", label: "Evidence" }, { id: "methodology", label: "Methodology" },
];
function Header({ title, copy }: { title: string; copy: string }) { return <header className="max-w-3xl"><h2 className="text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></header>; }
function Value({ value }: { value: number | null | undefined }) { return <>{value === null || value === undefined ? <span className="text-muted-foreground">Unavailable</span> : value}</>; }

export default function AnalysisCenter({ data }: { data: AnalysisCenterData }) {
  const [section, setSection] = useState<Section>("performance");
  const status = String(data.snapshot.mode || "unavailable");
  return <div>
    <div className="border border-border bg-muted/20 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Principal analytics · {status}</p><h1 className="mt-2 text-3xl font-semibold">{data.command_view.subject}</h1></div><p className="max-w-md text-sm text-muted-foreground">{data.snapshot.notice}</p></div></div>
    <nav className="analysis-rail mt-6" aria-label="Analysis Center sections">{sections.map((item) => <button key={item.id} type="button" onClick={() => setSection(item.id)} className={section === item.id ? "active" : ""}>{item.label}</button>)}</nav>
    <div className="mt-10">
      {section === "performance" && <section><Header title="Observed activity" copy="Counts below are source-backed records in the selected window. Momentum, favorability, search, and rank remain unavailable until their eligible snapshots exist." /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(data.activity_metrics || []).map((item) => <article key={item.key} className="border border-border p-5"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-3 text-2xl font-semibold">{item.value}</p><p className="mt-2 text-xs text-muted-foreground">Observed in {item.window}</p></article>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.momentum_components.map((item) => <article key={item.key} className="border border-dashed border-border p-4"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-2 text-sm font-semibold"><Value value={item.score} /></p></article>)}</div></section>}
      {section === "watchlist" && <section><Header title="Six-person research watchlist" copy="Equal-window activity comparisons for the maintained core six. These are research figures, not filed candidates." /><div className="mt-8 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="pb-3">Figure</th><th className="pb-3">Current</th><th className="pb-3">Previous</th><th className="pb-3">Change</th><th className="pb-3">Status</th></tr></thead><tbody>{data.watchlist.map((row) => <tr key={row.slug} className="border-b border-border/60"><td className="py-4"><strong>{row.name}</strong><p className="text-xs text-muted-foreground">{row.office || "Role unavailable"}</p></td><td className="py-4"><Value value={row.activity_current} /></td><td className="py-4"><Value value={row.activity_previous} /></td><td className="py-4"><Value value={row.movement} /></td><td className="py-4 text-xs">{row.evidence_status}</td></tr>)}</tbody></table></div></section>}
      {section === "national" && <section><Header title="National glossary radar" copy="Figures outside the core six are presented separately from the principal watchlist. No rank or performance inference is added." /><div className="mt-8 divide-y divide-border border-y border-border">{(data.national_radar || []).map((row) => <div key={row.slug} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><strong>{row.name}</strong><p className="text-xs text-muted-foreground">{row.office || "Role unavailable"}</p></div><span className="text-sm">{row.activity_current} observed · {row.evidence_status}</span></div>)}</div></section>}
      {section === "channels" && <section><Header title="Channel record" copy="These are source distributions, not effectiveness scores. Coverage is shown only when a denominator is known." /><div className="mt-8 divide-y divide-border border-y border-border">{data.channels.map((row) => <div key={row.name} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><strong>{row.name}</strong><p className="text-xs text-muted-foreground">{row.comparison}</p></div><span className="text-sm">Score: <Value value={row.score} /> · Coverage: <Value value={row.coverage === null ? null : Math.round(row.coverage * 100)} /></span></div>)}</div></section>}
      {section === "evidence" && <section><Header title="Evidence explorer" copy="Every row is linked to persisted source-backed evidence with capture time, layer, geography, and confidence." /><div className="mt-8 divide-y divide-border border-y border-border">{data.evidence.map((row) => <article key={row.id} className="py-5"><a href={row.url} target="_blank" rel="noreferrer" className="font-semibold text-[var(--signal-blue)]">{row.title} ↗</a><p className="mt-2 text-xs text-muted-foreground">{row.source} · {row.layer} · {row.geography} · {Math.round(row.classification_confidence * 100)}% confidence</p></article>)}{data.evidence.length === 0 && <p className="py-8 text-sm text-muted-foreground">No evidence is available for this window.</p>}</div></section>}
      {section === "methodology" && <section><Header title="Methodology and safeguards" copy="Evidence windows, freshness, provenance, and coverage accompany every live projection. Polling, synthetic audience work, and momentum are separate layers." /><div className="mt-8 border-l-4 border-[var(--signal-blue)] bg-[var(--signal-wash)] p-6 text-sm leading-7"><p><strong>Window:</strong> {String(data.snapshot.window || "7d")}</p><p><strong>Produced by:</strong> {String(data.snapshot.produced_by || "database projection")}</p><p><strong>Policy:</strong> Missing is null; rank is withheld without eligible coverage.</p><p><strong>Coverage:</strong> {data.coverage.note}</p></div></section>}
    </div>
  </div>;
}
