"""Audience Center structures and contracts."""
from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


class PersonalAudienceInstructions(BaseModel):
    """Instructions generated by the PersonalAudienceAgent for data extraction."""

    target_name: str = Field(..., description="Full name of the principal")
    aliases: list[str] = Field(default_factory=list, description="Common aliases/nicknames")
    focus_keywords: list[str] = Field(default_factory=list, description="Keywords to filter on")
    priority_topics: list[str] = Field(default_factory=list, description="Key personal topics/controversies to watch")
    extraction_fields: list[str] = Field(default_factory=list, description="Data points of interest (e.g., statements, media appearances)")
    instructions_summary: str = Field(..., description="Plain-text description of instructions for extraction")


class CompetitorsAudienceInstructions(BaseModel):
    """Instructions generated by the CompetitorsAudienceAgent for competitor intelligence extraction."""

    primary_competitors: list[str] = Field(default_factory=list, description="Names of competitors or political rivals")
    competitor_keywords: list[str] = Field(default_factory=list, description="Keywords to identify competitor content without using X vs Y format")
    topics_of_contention: list[str] = Field(default_factory=list, description="Policies, issues, or events of competitive debate")
    tracking_priorities: list[str] = Field(default_factory=list, description="What to extract specifically about rivals (alliances, attacks, policy shifts)")
    instructions_summary: str = Field(..., description="Plain-text description of instructions for extraction")


class ContextualAudienceInstructions(BaseModel):
    """Instructions generated by the ContextualAudienceAgent for contextual macro-environment monitoring."""

    target_regions: list[str] = Field(default_factory=list, description="Geographic regions, provinces, or cities to focus on")
    demographic_segments: list[str] = Field(default_factory=list, description="Audience/cohort segments of highest priority")
    salient_issues: list[str] = Field(default_factory=list, description="Trending socio-economic or political topics of relevance")
    instructions_summary: str = Field(..., description="Plain-text description of instructions for extraction")


class FacebookAnalysisCategoryResult(BaseModel):
    """Results extracted and synthesized from a specific category on Facebook."""

    category_name: str = Field(..., description="Name of the category (Personal, Competitors, Contextual)")
    sentiment_distribution: dict[str, float] = Field(default_factory=dict, description="Percentage of Positive, Neutral, Negative sentiment")
    top_themes: list[str] = Field(default_factory=list, description="Dominant topics or keywords extracted")
    engagement_metrics: dict[str, int] = Field(default_factory=dict, description="Total likes, shares, comments aggregated")
    key_findings: list[str] = Field(default_factory=list, description="Notable insights discovered from this category's Meta presence")


class FacebookAnalysisResult(BaseModel):
    """Data scraped from Facebook APIs and synthesized by the FacebookAnalysisAgent."""
    
    categories: list[FacebookAnalysisCategoryResult] = Field(default_factory=list, description="Results for each analyzed category")
    overall_landscape_summary: str = Field(..., description="Executive summary of the competitive landscape on Facebook")
    actionable_recommendations: list[str] = Field(default_factory=list, description="Strategic recommendations based on Facebook presence")


class AudienceInstructionsSummary(BaseModel):
    """Consolidated instructions wrapper for the Audience Center API and UI."""

    personal: PersonalAudienceInstructions | None = None
    competitors: CompetitorsAudienceInstructions | None = None
    contextual: ContextualAudienceInstructions | None = None
    facebook_analysis: FacebookAnalysisResult | None = None
    last_updated_at: str | None = None
